import type { Beverage, Store } from './types';

// Nombres de bebidas traducidos o mantenidos según su marca
export const mockBeverages: Beverage[] = [
  {
    id: 'bev1',
    name: 'Stolichnaya Vodka',
    type: 'Vodka',
    brand: 'Stolichnaya',
    price: 150.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Vodka ruso clásico, suave y puro.'
  },
  {
    id: 'bev2',
    name: 'Paceña Pilsener',
    type: 'Beer',
    brand: 'Paceña',
    price: 10.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Cerveza lager boliviana líder, refrescante y con cuerpo.'
  },
  {
    id: 'bev3',
    name: 'Vino Kohlberg Tinto',
    type: 'Wine',
    brand: 'Kohlberg',
    price: 55.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Vino tinto de altura, producido en los valles de Tarija.'
  },
  {
    id: 'bev4',
    name: 'Jameson Irish Whiskey',
    type: 'Whiskey',
    brand: 'Jameson',
    price: 180.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Whiskey irlandés tridestilado, excepcionalmente suave.'
  },
  {
    id: 'bev5',
    name: 'Cerveza Cordillera',
    type: 'Beer',
    brand: 'Cordillera',
    price: 12.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Cerveza artesanal boliviana con un toque especial.'
  },
  {
    id: 'bev6',
    name: 'Four Loko Gold',
    type: 'Other', 
    brand: 'Four Loko',
    price: 25.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Popular bebida de malta saborizada.'
  },
  {
    id: 'bev7',
    name: 'Coca-Cola Clásica',
    type: 'Other', 
    brand: 'Coca-Cola',
    price: 8.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Refresco de cola clásico.'
  },
  {
    id: 'bev8',
    name: 'Jägermeister',
    type: 'Other', 
    brand: 'Jägermeister',
    price: 160.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Licor de hierbas alemán, popular globalmente.'
  },
  {
    id: 'bev9',
    name: 'Fernet Branca',
    type: 'Other', 
    brand: 'Branca',
    price: 130.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Licor de hierbas amargo italiano, a menudo mezclado con cola.'
  },
  {
    id: 'bev10',
    name: 'Huari Tradicional',
    type: 'Beer',
    brand: 'Huari',
    price: 11.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Cerveza boliviana premium con un sabor equilibrado.'
  },
  {
    id: 'bev11',
    name: 'Singani Casa Real Etiqueta Negra',
    type: 'Other', 
    brand: 'Casa Real',
    price: 90.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Singani boliviano premium, destilado de uvas Moscatel de Alejandría.'
  },
  {
    id: 'bev12',
    name: 'Ron Abuelo Añejo',
    type: 'Other', 
    brand: 'Ron Abuelo',
    price: 140.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Ron panameño añejo, suave y rico.'
  },
  {
    id: 'bev13',
    name: 'Sprite',
    type: 'Other', 
    brand: 'Sprite',
    price: 7.00, 
    imageUrl: 'https://placehold.co/300x400.png',
    description: 'Refresco de lima-limón.'
  }
];

export const mockStores: Store[] = [
  // Tiendas Originales (con inventario actualizado para más variedad)
  {
    id: 'store1',
    name: 'Licorería El Gato Negro',
    address: 'Av. Busch #750, Primer Anillo',
    hours: 'Lun-Sáb: 10am-9pm, Dom: 12pm-6pm',
    photos: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    latitude: -17.7739, 
    longitude: -63.1812, 
    inventory: [
      { beverageId: 'bev1', stock: 10 }, { beverageId: 'bev2', stock: 25 },
      { beverageId: 'bev9', stock: 7 }, { beverageId: 'bev10', stock: 12 },
      { beverageId: 'bev7', stock: 30 }, { beverageId: 'bev11', stock: 8 },
    ],
    rating: 4.5,
  },
  {
    id: 'store2',
    name: 'Supermercado Fidalga Equipetrol',
    address: 'Av. San Martín, Equipetrol Norte',
    hours: 'Lun-Dom: 9am-10pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7695, 
    longitude: -63.1948, 
    inventory: [
      { beverageId: 'bev1', stock: 3 }, { beverageId: 'bev2', stock: 40 },
      { beverageId: 'bev3', stock: 15 }, { beverageId: 'bev5', stock: 12 },
      { beverageId: 'bev6', stock: 10 }, { beverageId: 'bev8', stock: 5 },
      { beverageId: 'bev13', stock: 20 },
    ],
    rating: 4.2,
  },
  {
    id: 'store3',
    name: 'Bodega La Sommelier',
    address: 'Calle René Moreno #230, Casco Viejo',
    hours: 'Lun-Sáb: 11am-9pm, Dom: Cerrado',
    photos: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    latitude: -17.7863, 
    longitude: -63.1812, 
    inventory: [
      { beverageId: 'bev3', stock: 20 }, { beverageId: 'bev4', stock: 7 },
      { beverageId: 'bev1', stock: 2 }, { beverageId: 'bev8', stock: 6 },
      { beverageId: 'bev12', stock: 9 }, { beverageId: 'bev11', stock: 10 },
    ],
    rating: 4.8,
  },
  // --- NUEVAS TIENDAS ---
  {
    id: 'store4',
    name: 'El Pozito de la Beni',
    address: 'Av. Beni, entre 2do y 3er Anillo',
    hours: 'Lun-Dom: 24 horas',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7652,
    longitude: -63.1825,
    inventory: [
      { beverageId: 'bev2', stock: 100 }, { beverageId: 'bev10', stock: 50 },
      { beverageId: 'bev7', stock: 80 }, { beverageId: 'bev13', stock: 60 },
      { beverageId: 'bev9', stock: 5 },
    ],
    rating: 4.6,
  },
  {
    id: 'store5',
    name: 'Planeta Bebidas',
    address: 'Av. Cristo Redentor, 4to Anillo',
    hours: 'Lun-Jue: 10am-10pm, Vie-Sáb: 10am-12am',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7558,
    longitude: -63.1745,
    inventory: [
      { beverageId: 'bev1', stock: 15 }, { beverageId: 'bev4', stock: 10 },
      { beverageId: 'bev6', stock: 20 }, { beverageId: 'bev8', stock: 12 },
      { beverageId: 'bev12', stock: 18 },
    ],
    rating: 4.7,
  },
  {
    id: 'store6',
    name: 'Supermercado Hipermaxi Roca y Coronado',
    address: 'Av. Roca y Coronado, 3er Anillo',
    hours: 'Lun-Dom: 8am-10pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7851,
    longitude: -63.2045,
    inventory: [
      { beverageId: 'bev2', stock: 120 }, { beverageId: 'bev3', stock: 40 },
      { beverageId: 'bev7', stock: 200 }, { beverageId: 'bev10', stock: 80 },
      { beverageId: 'bev11', stock: 25 },
    ],
    rating: 4.4,
  },
  {
    id: 'store7',
    name: 'Full Copas',
    address: 'Av. Santos Dumont, 5to Anillo',
    hours: 'Lun-Sáb: 3pm-11pm, Dom: Cerrado',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.8248,
    longitude: -63.1751,
    inventory: [
      { beverageId: 'bev9', stock: 15 }, { beverageId: 'bev6', stock: 30 },
      { beverageId: 'bev8', stock: 8 }, { beverageId: 'bev1', stock: 0 },
    ],
    rating: 4.3,
  },
  {
    id: 'store8',
    name: 'La Cava del Sur',
    address: 'Av. La Salle, Zona Sur',
    hours: 'Lun-Sáb: 10am-8pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.8085,
    longitude: -63.1890,
    inventory: [
      { beverageId: 'bev3', stock: 50 }, { beverageId: 'bev11', stock: 20 },
      { beverageId: 'bev12', stock: 15 }, { beverageId: 'bev4', stock: 5 },
    ],
    rating: 4.9,
  },
  {
    id: 'store9',
    name: 'Licorería El Bajío',
    address: 'Calle 5, Barrio El Bajío',
    hours: 'Lun-Dom: 11am-11pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.8089,
    longitude: -63.2033,
    inventory: [
      { beverageId: 'bev2', stock: 80 }, { beverageId: 'bev10', stock: 40 },
      { beverageId: 'bev5', stock: 20 }, { beverageId: 'bev7', stock: 50 },
    ],
    rating: 4.0,
  },
  {
    id: 'store10',
    name: 'Micromarket Lucho',
    address: 'Av. Piraí, entre 2do y 3er Anillo',
    hours: 'Lun-Sáb: 8am-10pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7891,
    longitude: -63.1956,
    inventory: [
      { beverageId: 'bev2', stock: 30 }, { beverageId: 'bev7', stock: 40 },
      { beverageId: 'bev13', stock: 25 }, { beverageId: 'bev9', stock: 3 },
    ],
    rating: 3.9,
  },
  {
    id: 'store11',
    name: 'The Wine Cellar - Urubó',
    address: 'Colinas del Urubó, Av. Principal',
    hours: 'Mar-Sáb: 11am-8pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7758,
    longitude: -63.2201,
    inventory: [
      { beverageId: 'bev3', stock: 60 }, { beverageId: 'bev4', stock: 20 },
      { beverageId: 'bev12', stock: 15 }, { beverageId: 'bev11', stock: 30 },
    ],
    rating: 4.9,
  },
  {
    id: 'store12',
    name: 'Estación de Cervezas (Cambódromo)',
    address: 'Av. Mutualista, frente al Cambódromo',
    hours: 'Vie-Dom: 6pm-2am',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7602,
    longitude: -63.1698,
    inventory: [
      { beverageId: 'bev2', stock: 200 }, { beverageId: 'bev5', stock: 100 },
      { beverageId: 'bev10', stock: 150 }, { beverageId: 'bev6', stock: 50 },
    ],
    rating: 4.5,
  },
  {
    id: 'store13',
    name: 'Licorería Amigo (Villa 1ro de Mayo)',
    address: 'Av. Cumavi, UV 158',
    hours: 'Lun-Dom: 9am-10pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.8077,
    longitude: -63.1425,
    inventory: [
      { beverageId: 'bev2', stock: 150 }, { beverageId: 'bev9', stock: 20 },
      { beverageId: 'bev7', stock: 100 }, { beverageId: 'bev1', stock: 5 },
    ],
    rating: 4.1,
  },
  {
    id: 'store14',
    name: 'Bodegón de Vinos - Sirari',
    address: 'Barrio Sirari, Calle Las Dalias #25',
    hours: 'Lun-Sáb: 10am-8pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7711,
    longitude: -63.1999,
    inventory: [
      { beverageId: 'bev3', stock: 80 }, { beverageId: 'bev4', stock: 10 },
      { beverageId: 'bev12', stock: 0 }, { beverageId: 'bev11', stock: 22 },
    ],
    rating: 4.7,
  },
  {
    id: 'store15',
    name: 'Mundo Bebidas 24/7',
    address: 'Segundo Anillo, esq. Av. La Barranca',
    hours: 'Lun-Dom: 24 horas',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7955,
    longitude: -63.1670,
    inventory: [
      { beverageId: 'bev6', stock: 40 }, { beverageId: 'bev1', stock: 12 },
      { beverageId: 'bev8', stock: 10 }, { beverageId: 'bev2', stock: 60 },
    ],
    rating: 4.2,
  },
  {
    id: 'store16',
    name: 'Parada 7',
    address: 'Av. Alemana, entre 6to y 7mo Anillo',
    hours: 'Lun-Sáb: 9am-9pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7381,
    longitude: -63.1702,
    inventory: [
        { beverageId: 'bev5', stock: 30 }, { beverageId: 'bev10', stock: 50 },
        { beverageId: 'bev13', stock: 40 },
    ],
    rating: 4.0,
  },
  {
    id: 'store17',
    name: 'Licorería El Pari',
    address: 'Mercado El Pari, Zona Comercial',
    hours: 'Lun-Sáb: 8am-7pm',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7971,
    longitude: -63.1844,
    inventory: [
        { beverageId: 'bev2', stock: 250 }, { beverageId: 'bev9', stock: 30 },
        { beverageId: 'bev11', stock: 40 }, { beverageId: 'bev7', stock: 150 },
    ],
    rating: 4.3,
  },
  {
    id: 'store18',
    name: 'Marriott Hotel Bar',
    address: 'Cuarto Anillo, Equipetrol',
    hours: 'Lun-Dom: 5pm-2am',
    photos: ['https://placehold.co/600x400.png'],
    latitude: -17.7659,
    longitude: -63.1932,
    inventory: [
        { beverageId: 'bev1', stock: 8 }, { beverageId: 'bev4', stock: 12 },
        { beverageId: 'bev3', stock: 20 }, { beverageId: 'bev8', stock: 6 },
    ],
    rating: 5.0,
  }
];
